//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by REMOTE.rc
//
#define IDC_PB_HELP                     9
#define IDD_NETWORK                     100
#define IDD_DEVICE                      101
#define IDD_MOTION                      102
#define IDD_DRVF_MOTION                 108
#define IDC_E_ST_VEL                    110
#define IDC_E_MAX_VEL                   111
#define IDC_E_TACC                      112
#define IDD_DRVF_MOTION_INT             112
#define IDC_E_SVACC                     113
#define IDD_DRVF_MOTION_F64             113
#define IDC_E_SVDEC                     114
#define IDC_E_TDEC                      115
#define IDC_E_POSX                      116
#define IDC_E_POSY                      117
#define IDC_E_POSZ                      118
#define IDC_E_POSU                      119
#define IDC_E_CX                        120
#define IDC_E_CY                        121
#define IDD_DRVF_SETGET                 121
#define IDC_E_EX                        122
#define IDC_E_EY                        123
#define IDC_E_ORGOFFLIMIT               124
#define IDD_DRVF_MOTION_INTERP          125
#define IDC_CB_SIMULATE                 203
#define IDC_CB_CRITICAL                 205
#define IDC_RB_8_CHANNELS               208
#define IDC_RB_PCI7851                  208
#define IDC_RB_16_CHANNELS              209
#define IDC_RB_PCI7852                  209
#define IDC_RB_PCI7853                  210
#define IDC_RB_16_CHANNELS3             211
#define IDC_RB_PCI7854                  211
#define IDC_CO_ADDRESS                  219
#define IDC_CO_IO_ADDRESS               220
#define IDC_CO_ID                       220
#define IDC_CO_OUTMODE                  221
#define IDC_CO_IO_SWAP                  222
#define IDC_CO_IPTMODE                  222
#define IDC_CO_CNTSCR                   223
#define IDC_CO_ALM_LOGIC                224
#define IDC_CO_ALM_RESP                 225
#define IDC_CO_INP_LOGIC                226
#define IDC_E_STATUS                    226
#define IDC_CO_ENCLOGIC                 227
#define IDC_CO_INP_MODE                 228
#define IDC_E_RESULT                    228
#define IDC_CO_ORG_LOGIC                229
#define IDC_E_POS                       229
#define IDC_CO_LIMIT_RESP               230
#define IDC_E_OPT_DIR                   230
#define IDC_CO_ERC_LOGIC                231
#define IDC_E_AXIS_ARRAY                231
#define IDC_CO_EZ_LOGIC                 232
#define IDC_CO_SD_MODE                  233
#define IDC_CO_SD_LOGIC                 234
#define IDC_CO_SD_RESP                  235
#define IDC_CO_SD_LATCH                 236
#define IDC_CO_LTC_LOGIC                237
#define IDC_CO_HOME_MODE                238
#define IDC_CO_CNT_SCR                  239
#define IDC_CO_LTC_COUNTER              240
#define IDC_CO_SERVO_STATE              240
#define IDC_CO_AXIS                     241
#define IDC_CO_PCI_INDEX                301
#define IDC_CO_PCI_COUNT                302
#define IDC_C_AXIS_NO                   302
#define IDC_CO_PCI_MODEL                303
#define IDC_C_AXIS_FUNCTION             303
#define IDC_CO_PCI_MAX_ADDR             304
#define IDC_CO_PCI_TRATE                304
#define IDC_E_SET                       304
#define IDC_C_CHANNEL                   304
#define IDC_CO_PCI_MAX_ADDR2            305
#define IDC_E_SET_ARRAYSIZE             305
#define IDC_E_SETI16_1                  317
#define IDC_E_SETF64_1                  318
#define IDC_E_GETI32                    318
#define IDC_E_SETI16_2                  319
#define IDC_E_SETI16_3                  320
#define IDC_E_GET                       320
#define IDC_E_SETI16_4                  321
#define IDC_E_SETI16_5                  322
#define IDC_E_GETF64                    323
#define IDC_E_SETF64_2                  324
#define IDC_E_SETF64_3                  325
#define IDC_E_SETF64_4                  326
#define IDC_E_SETF64_5                  327
#define IDS_CP_SOFTWARE_FAULT           1000
#define IDS_CP_TOO_MANY_DRIVERS         1001
#define IDS_CP_DRIVER_NOT_CONFIGURED    1002
#define IDS_CP_DEVICE_NOT_CONFIGURED    1003
#define IDS_CP_UNKNOWN_DEVICE           1004
#define IDS_CP_NO_DEVICES               1005
#define IDS_CP_NETPASS1_ERROR           1006
#define IDS_CP_UNKNOWN_ACCESS           1007
#define IDS_CP_NO_INPUTS                1008
#define IDS_CP_NO_OUTPUTS               1009
#define IDS_CP_NO_MEMORY                1010
#define IDS_CP_NETCONFIG_ID             1011
#define IDS_CP_NETCONFIG_VERS           1012
#define IDS_CP_NETCONFIG_DPADR          1013
#define IDS_CP_NETCONFIG_PORT           1015
#define IDS_CP_NETCONFIG_WATCHDOG       1016
#define IDS_CP_NETCONFIG_HWTEST         1017
#define IDS_CP_NETCONFIG_STOPSTATE      1018
#define IDS_CP_NETCONFIG_SIMULATE       1019
#define IDS_CP_NETCONFIG_BAUDRATE       1020
#define IDS_CP_NETCONFIG_IRQ            1021
#define IDS_CP_NETCONFIGSIZE            1022
#define IDS_CP_SAME_DPRADR              1023
#define IDS_CP_SAME_PORT                1024
#define IDS_CP_SAME_IRQ                 1025
#define IDS_CP_DEVCONFIG_NETID          1026
#define IDS_CP_DEVCONFIG_ID             1027
#define IDS_CP_DEVCONFIG_VERS           1028
#define IDS_CP_DEVCONFIG_ADDRESS        1030
#define IDS_CP_DEVCONFIG_CRITICAL       1032
#define IDS_CP_DEVCONFIG_ERR            1035
#define IDS_CP_DEVCONFIG_INVALID_PCODE  1036
#define IDS_CP_OVERLAPP                 1040
#define IDS_CP_SAME_DP_ADDRESS          1041
#define IDS_CP_SAME_DEVICE_ADDRESS      1042
#define IDS_CP_DEVCONFIGFIELD           1043
#define IDS_CP_DEVCONFIGSIZE            1050
#define IDS_CP_CANNOT_GET_DEVCONFIG     1051
#define IDS_CP_CANNOT_GET_NETCONFIG     1052
#define IDS_CP_INVALID_PORT             1053
#define IDS_CP_INVALID_DPR              1054
#define IDS_CP_INVALID_STOPSTATE        1055
#define IDS_CP_INVALID_BAUDRATE         1056
#define IDS_CP_INVALID_POINT            1057
#define IDS_CP_POINT_OUTSIDE            1058
#define IDS_CP_INVALID_IRQLEVEL         1059
#define IDS_CP_POINT_OVERLAP            1060
#define IDS_CP_CANNOT_FIND_NETWORK      1061
#define IDS_CP_SAME_PCI_INDEX           1062
#define IDS_CP_INCONSISTENT_PCI_COUNT   1063
#define IDS_INVALID_PCI_INDEX           1064
#define IDS_INVALID_PCI_COUNT           1065
#define IDS_PCI_INDEX_TOO_BIG           1066

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        800
#define _APS_NEXT_COMMAND_VALUE         4000
#define _APS_NEXT_CONTROL_VALUE         303
#define _APS_NEXT_SYMED_VALUE           2000
#endif
#endif
